Repository Jungle-5pointers/5_pointers, pull requests merged in 2025-07, with the labels that each got.

#65 yjs 협업 기능
  COLLABORATION_README.md
  frontend/src/components/collaboration/CommentSystem.jsx
  frontend/src/components/collaboration/LiveCursors.jsx
  frontend/src/components/collaboration/VersionHistory.jsx
  frontend/src/hooks/useCollaboration.js
  frontend/src/hooks/useComments.js
  frontend/src/hooks/useLiveCursors.js
  frontend/src/hooks/useVersionHistory.js
  frontend/src/hooks/useYjsCollaboration.js
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/components/definitions/index.js
  yjs-server-package.json
  yjs-server.js
Labels: 배민재민

#70 62 canvasarea 충돌방지 확장기능 초기상태 스냅라인 깔뽕
  frontend/src/components/collaboration/CommentSystem.jsx
  frontend/src/components/collaboration/VersionHistory.jsx
  frontend/src/hooks/useCollaboration.js
  frontend/src/hooks/useComments.js
  frontend/src/hooks/useVersionHistory.js
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/BankAccountRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/CalendarRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/CommentRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/DdayRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/GridGalleryRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/SlideGalleryRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingContactRenderer.jsx
  frontend/src/pages/NoCodeEditor/PreviewModal.jsx
  frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
Labels: 배민재민

#72 템플릿 제작 기능 구현
  backend/src/app.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt.strategy.ts
  backend/src/common/guards/template-admin.guard.ts
  backend/src/templates/templates.controller.ts
  backend/src/templates/templates.module.ts
  backend/src/templates/templates.service.ts
  backend/src/users/entities/pages.entity.ts
  backend/src/users/entities/templates.entity.ts
  backend/src/users/entities/users.entity.ts
  backend/src/users/users.service.ts
  frontend/src/pages/DashboardPage.jsx
  frontend/src/pages/NoCodeEditor.jsx
Labels: 올영김별

#73 editor very upgrade
  frontend/src/components/collaboration/LiveCursors.jsx
  frontend/src/hooks/useLiveCursors.js
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  package-lock.json
  package.json
  yjs-server.js
Labels: 배민재민

#74 안내장 컴포넌트 생성
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/WeddingInviteEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
  frontend/src/pages/NoCodeEditor/ComponentRenderers/MapInfoRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingInviteRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/components/definitions/index.js
  frontend/src/pages/components/definitions/wedding-invite.json
Labels: 인프세창

#75 근래 최고의 코드
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
  frontend/src/pages/NoCodeEditor/components/TemplateModal.jsx
  frontend/src/pages/NoCodeEditor/components/UserCursor.jsx
  frontend/src/pages/NoCodeEditor/utils/editorUtils.js
Labels: 배민재민

#79 안내장 컴포넌트 수정
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingInviteRenderer.jsx
Labels: 인프세창

#83 템플릿 오류 수정
  frontend/src/pages/NoCodeEditor.jsx
Labels: 올영김별

#82 WeddingInvite 관련 기능 구현 및 오류 수정
  frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  frontend/src/pages/NoCodeEditor/utils/editorUtils.js
Labels: 인프세창

#85 컴포넌트 렌더링 수정
  frontend/src/hooks/useCollaboration.js
  frontend/src/pages/NoCodeEditor.jsx
Labels: 올영김별

#89 Music
  frontend/.gitignore
  frontend/src/data/musicLibrary.js
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/MusicEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
  frontend/src/pages/NoCodeEditor/ComponentRenderers/MusicRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  frontend/src/pages/components/definitions/index.js
  frontend/src/pages/components/definitions/music.json
Labels: 인프세창

#91 ComponentEditor.jsx의 import 수정
  frontend/src/pages/NoCodeEditor/ComponentEditor.jsx
Labels: 인프세창

#96 튼튼한 성 - 파괴된 성을 재건했다.
  backend/src/auth/jwt.strategy.ts
  frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
Labels: 배민재민

#97 inspector.jsx에서 music관련 빠진 부분 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/NoCodeEditor/Inspector.jsx
Labels: 인프세창

#103 기능이 일부 소실
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
  frontend/src/pages/NoCodeEditor.jsx
Labels: 배민재민

#114 자동저장, 협업기능 개잘됨
  my-web-builder/.turbo/cookies/9.cookie
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx.clean
  yjs-server.js
Labels: 배민재민

#127 Component library thumbnail fix #116
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary.backup.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary.original.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/ComponentCard.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/ComponentGrid.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/DeploySection.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/LibraryHeader.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/SearchBar.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/ToggleButton.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/hooks/useDeploy.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/AttendThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/BankAccountThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/ButtonThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/CalendarThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/CommentThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/DdayThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/DefaultThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/GridGalleryThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/ImageThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/LinkThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/MapThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/MusicThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/SlideGalleryThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/TextThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/WeddingContactThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/WeddingInviteThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/index.js
  my-web-builder/apps/frontend/src/pages/components/definitions/index.js
  my-web-builder/apps/frontend/src/pages/components/definitions/map.json
Labels: 펍지준배

#146 AWS git action test
  my-web-builder/.turbo/cookies/1.cookie
  my-web-builder/.turbo/cookies/2.cookie
  my-web-builder/apps/frontend/src/pages/MainPage.jsx
Labels: 배민재민

#147 Add frontend workflow
  .github/workflows/5pointers-frontend-deploy.yml
Labels: 올영김별

#211 google oauth git action 설정
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/frontend/src/config.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/Inspector.jsx
Labels: 배민재민

#219 카카오 구글 로그인 테스트
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
Labels: 배민재민

#223 초대 오류 고침 제발 고장나지말아라
  my-web-builder/apps/frontend/src/pages/InvitationHandler.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
Labels: 배민재민

#224 이제 진짜 됨 메이비
  .github/workflows/deploy-backend.yml
  .github/workflows/subdomain-server.yml
  DEPLOYMENT_UPDATES.md
  GITHUB_SECRETS_SETUP.md
  deployment-script.sh
  fix-subdomain-deployment.sh
  get-instance-id.sh
  setup-ssm-agent.sh
  subdomain-server.js
Labels: 스크영준

#228 Subdomain fixing
  .github/workflows/subdomain-server.yml
  create-new-subdomain-ec2.sh
  subdomain-server.js
Labels: 스크영준

#231 Add page component
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  my-web-builder/apps/frontend/src/hooks/useComponentActions.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/PageEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/PageThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/index.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/PageRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/Inspector.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/PageNavigation.jsx
  my-web-builder/apps/frontend/src/pages/components/definitions/index.js
  my-web-builder/apps/frontend/src/pages/components/definitions/page.json
Labels: 펍지준배

#233 Remove redundant subdomain-server.yml - now integrated in backend EB
  .github/workflows/deploy-backend.yml
  .github/workflows/subdomain-server.yml
Labels: 배민재민

#239 yjs 인스턴스 생성, 컨트롤 C V A, 드래그
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/frontend/src/config.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  yjs-server.js
Labels: 배민재민

#240 VITE_YJS_WEBSOCKET_URL 변경
  my-web-builder/apps/frontend/.env.staging
Labels: 배민재민

#241 yjs vite websocket url
  my-web-builder/apps/frontend/src/config.js
Labels: 배민재민

#244 fix: 중복된 Templates import 제거
  backend/src/app.module.ts
Labels: 펍지준배

#246 🚀 Y.js 협업 기능 복구 완료
  README.md
  YJS_TROUBLESHOOTING.md
  my-web-builder/apps/frontend/.env.staging
  my-web-builder/apps/frontend/src/config.js
  my-web-builder/apps/frontend/src/hooks/useCollaboration.js
  my-web-builder/apps/frontend/src/hooks/useYjsCollaboration.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  setup-remote-yjs.sh
  start-yjs-server.sh
  yjs-server-userdata.sh
Labels: 배민재민

#247 236 yjs deploy
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/frontend/src/config.js
Labels: 배민재민

#248 🔒 Y.js 서버 SSL 인증서 설정 완료
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/frontend/src/config.js
Labels: 배민재민

#250 🔧 임시로 HTTP WebSocket 사용 (Mixed Content 이슈 해결)
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/frontend/src/config.js
Labels: 배민재민

#251 🔒 WSS 사용으로 Mixed Content 오류 해결
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/frontend/src/config.js
Labels: 배민재민

#255 🔒 WSS + 사용자 안내 UI로 WebSocket 연결 문제 해결
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/frontend/src/components/WebSocketConnectionGuide.jsx
  my-web-builder/apps/frontend/src/config.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
Labels: 배민재민

#257 🧹 Remove debug console logs
  my-web-builder/apps/frontend/src/hooks/useComponentActions.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
Labels: 배민재민

#258 region 수정
  backend/src/s3/s3.service.ts
Labels: 펍지준배

#259 찐막 s3업로드 수정
  backend/src/s3/s3.service.ts
Labels: 펍지준배

#260 반응형 일단 합침 미완성
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/styles/preview.css
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
Labels: 올영김별

#264 🔧 Fix SPA routing issues
  create-jungle-database.js
  fix-spa-routing.sh
  my-web-builder/apps/frontend/public/.htaccess
  my-web-builder/apps/frontend/public/404.html
  my-web-builder/apps/frontend/public/_redirects
  my-web-builder/apps/frontend/vite.config.ts
Labels: 배민재민

#283 Apply pr268 only
  backend/src/app.module.ts
  my-web-builder/apps/frontend/package-lock.json
  my-web-builder/apps/frontend/package.json
  my-web-builder/apps/frontend/src/components/PageCanvasPreview.jsx
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/hooks/useEditorInteractionManager.js
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ButtonRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ImageRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/PageButtonRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/PageRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
  my-web-builder/packages/shared-components/package.json
  my-web-builder/packages/shared-components/src/index.ts
  mysql-mcp-server/package.json
  mysql-mcp-server/src/index.ts
  mysql-mcp-server/tsconfig.json
Labels: 배민재민

#287 웨딩 템플릿 편집기준 모바일로만 고정
  my-web-builder/apps/frontend/src/hooks/useEditorInteractionManager.js
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
Labels: 올영김별

#292 289 upgrade project - 템플릿 저장, 자동저장, 지도 에디터 수정
  backend/src/templates/templates.controller.ts
  backend/src/templates/templates.service.ts
  backend/src/users/users.service.ts
  my-web-builder/apps/frontend/src/components/PageCanvasPreview.jsx
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/hooks/useAutoSave.js
  my-web-builder/apps/frontend/src/hooks/useComponentActions.js
  my-web-builder/apps/frontend/src/hooks/usePageDataManager.js
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/AttendThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MapView.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/TemplateModal.jsx
  my-web-builder/apps/frontend/src/pages/components/definitions/kakaotalk-share.json
  my-web-builder/package-lock.json
  my-web-builder/package.json
Labels: 배민재민

#301 지도 에디터, 캔버스, 배포했을 때 동일하게 적용
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/maps/maps.controller.ts
  backend/src/maps/maps.module.ts
  my-web-builder/apps/subdomain-nextjs/components/renderers/MapView.jsx
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
  package-lock.json
  package.json
Labels: 배민재민

#302 편집 기준 모바일일 때 캔버스 중앙에 위치
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
Labels: 배민재민

#303 컴포넌트 선택 클릭아니고, 컨트롤 클릭해야지 다중선택 이영준 빡침 해결완료
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
Labels: 배민재민

#304 안내장 컴포넌트 렌더링 관련 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/WeddingInviteEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingInviteRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  my-web-builder/apps/frontend/src/pages/components/definitions/wedding-invite.json
Labels: 인프세창

#312 모바일 캔버스 중간, 뷰포트 모바일, 데스크톱 컬럼 추가
  backend/src/migrations/add-editing-mode-to-templates.sql
  backend/src/templates/templates.controller.ts
  backend/src/templates/templates.service.ts
  backend/src/users/entities/templates.entity.ts
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/hooks/useComponentActions.js
  my-web-builder/apps/frontend/src/hooks/useEditorInteractionManager.js
  my-web-builder/apps/frontend/src/hooks/usePageDataManager.js
  my-web-builder/apps/frontend/src/pages/Dashboard.jsx
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
Labels: 배민재민

#315 대시보드 미리보기 모바일, 데스크톱 구분
  backend/src/templates/templates.controller.ts
  backend/src/templates/templates.service.ts
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ViewportController.jsx
Labels: 배민재민

#317 컨트롤 클릭시 다중선택
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
Labels: 배민재민

#316 배포화면 반응형 1차 완성
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/ImageEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  my-web-builder/apps/subdomain-nextjs/components/renderers/ButtonRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/CommentRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/DdayRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/SlidoRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/WeddingInviteRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 올영김별

#324 빈 큐브 시작을 테마 밑으로 옮김
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingContentRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
Labels: 배민재민

#327 웨딩콘텐츠랜더러 치트코드 삭제
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingContentRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
Labels: 배민재민

#326 링크복사 컴포넌트 생성
  backend/src/main.ts
  my-web-builder/apps/frontend/public/icons/linkcopy.png
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/LinkCopyThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/index.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/LinkCopyRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  my-web-builder/apps/frontend/src/pages/components/definitions/index.js
  my-web-builder/apps/frontend/src/pages/components/definitions/linkcopy.json
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
Labels: 인프세창

#329 데스크톱 미리보기도 완벽함
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
Labels: 배민재민

#333 Add mobile view #298
  backend/src/main.ts
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/styles/preview.css
  test-packages.js
Labels: 펍지준배

#334 자잘한 문제 제거
  backend/src/invitations/invitations.module.ts
  backend/src/invitations/invitations.service.ts
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/hooks/useCollaboration.js
  my-web-builder/apps/frontend/src/hooks/useComponentActions.js
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/InviteModal.jsx
Labels: 배민재민

#337 fix: 터짐 해결
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
Labels: 올영김별

#340 fix: 터짐 해결
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/CalendarRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/DdayRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/GridGalleryRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ImageRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/LinkCopyRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MapInfoRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MapView.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MusicRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/PageButtonRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingInviteRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MusicRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/PageButtonRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/PageRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/WeddingInviteRenderer.jsx
Labels: 올영김별

#341 템플릿 상태에서 초대하면 뷰포트, 템플릿 모드 유지 된 상태로 초대 수락하면 그 페이지로 이동
  backend/src/invitations/dto/create-invitation.dto.ts
  backend/src/invitations/invitations.service.ts
  backend/src/migrations/add-viewport-fromtemplate-to-page-members.sql
  backend/src/users/entities/page_members.entity.ts
  my-web-builder/apps/frontend/src/App.tsx
  my-web-builder/apps/frontend/src/components/InvitationNotifications.jsx
  my-web-builder/apps/frontend/src/components/NotificationToggle.jsx
  my-web-builder/apps/frontend/src/hooks/useYjsCollaboration.js
  my-web-builder/apps/frontend/src/pages/InvitationHandler.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/InviteModal.jsx
Labels: 배민재민

#332 UI fixing - 계좌안내 충돌 해결
  my-web-builder/apps/frontend/index.html
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/CommentEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/TextComponentEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/BankAccountRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ButtonRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/CommentRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MapInfoRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/FontFamilyEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
Labels: 스크영준

#348 Fix: 로컬에서 이미지 업로드 및 잔버그
  backend/src/generator/generator.service.ts
  backend/src/invitations/invitations.gateway.ts
  backend/src/main.ts
  backend/src/users/users.controller.ts
  my-web-builder/apps/frontend/src/components/InvitationNotifications.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/PageNavigation.jsx
Labels: 펍지준배

#350 페이지 멤버 표시 기능 구현
  .github/workflows/deploy-backend.yml.backup
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  my-web-builder/apps/frontend/src/hooks/usePageMembers.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/InviteModal.jsx
  my-web-builder/apps/frontend/src/utils/userUtils.js
Labels: 배민재민

#359 slido 크기 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
Labels: 인프세창

#362 Fix: 페이지 네비게이션 삭제
  backend/src/users/users.controller.ts
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/PageNavigation.jsx
Labels: 펍지준배

#364 링크복사 컴포넌트 이미지 서브도메인 폴더에 추가
  my-web-builder/apps/subdomain-nextjs/public/icons/linkcopy.png
Labels: 인프세창

#367 페이지 컴포넌트 테두리 제거 추가
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/PageEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/PageRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  my-web-builder/apps/frontend/src/pages/components/definitions/page.json
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
Labels: 인프세창

#376 Feat: 음악파일 S3에 업로드함
  my-web-builder/apps/frontend/src/data/musicLibrary.js
Labels: 펍지준배

#378 임시저장, 배포된 페이지에서 대시보드 버튼 제거, 배포 뒤 대시보드로 자동이동 제거
  aws/README.md
  aws/THIRD_PARTY_LICENSES
  aws/install
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
  my-web-builder/apps/frontend/src/pages/DraftsPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
Labels: 배민재민

#387 음악 이모티콘 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MusicEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MusicRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MusicRenderer.jsx
Labels: 인프세창

#390 반응형 서브도메인에 적용 완료
  backend/src/generator/generator.service.ts
  backend/src/users/entities/pages.entity.ts
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/AttendEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  my-web-builder/apps/frontend/src/pages/components/definitions/attend.json
  my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/BankAccountRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/ButtonRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/CalendarRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/CommentRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/DdayRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/GridGalleryRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/LinkCopyRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/LinkRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MapInfoRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MapView.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/SlideGalleryRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/SlidoRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/WeddingContactRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/WeddingInviteRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/hooks/useResponsive.js
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 올영김별

#399 이미지 컴포넌트 드래그 문제 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ImageRenderer.jsx
Labels: 인프세창

#407 feat: Y.js WebSocket 서버 IP 주소 업데이트 (43.201.xxxxxx → 13.124.xxxxx)
  README.md
  my-web-builder/apps/frontend/src/config.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
Labels: 배민재민

#408 deploy-frontend
  .github/workflows/deploy-frontend.yml
Labels: 배민재민

#412 일단 mixed content HTTP
  my-web-builder/apps/frontend/src/config.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
Labels: 배민재민

#417 406 all UI
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/frontend/public/ddukddak-logo.png
  my-web-builder/apps/frontend/src/components/InvitationNotifications.jsx
  my-web-builder/apps/frontend/src/components/PageCanvasPreview.jsx
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/config.js
  my-web-builder/apps/frontend/src/index.css
  my-web-builder/apps/frontend/src/pages/Dashboard.jsx
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
  my-web-builder/apps/frontend/src/pages/DraftsPage.jsx
  my-web-builder/apps/frontend/src/pages/LoginPage.jsx
  my-web-builder/apps/frontend/src/pages/MainPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/DeploySection.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendanceSummary.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/LinkRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
  my-web-builder/apps/frontend/src/pages/SocialCallbackPage.jsx
  my-web-builder/apps/frontend/src/styles/colors.js
  my-web-builder/apps/frontend/src/styles/global.css
  my-web-builder/apps/frontend/src/styles/pageColors.js
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
  my-web-builder/apps/subdomain-nextjs/package.json
  my-web-builder/pnpm-lock.yaml
Labels: 올영김별

#420 즐거운 색칠놀이
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
  my-web-builder/apps/frontend/src/pages/DraftsPage.jsx
  my-web-builder/apps/frontend/src/pages/LoginPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
Labels: 펍지준배

#421 근래 최고의 작품:local 환경에서 모든 기능이 거의 완벽함, 잡다한 오류는 좀 있음, yjs 서버 중간에 방 삭제되는 버그
  README.md
  TEMPLATE_SYNC_USAGE.md
  YJS_TROUBLESHOOTING.md
  backend/src/migrations/add-editing-mode-to-pages.sql
  collaboration-server.js
  my-web-builder/apps/frontend/src/App.tsx
  my-web-builder/apps/frontend/src/components/CollaborationStatus.jsx
  my-web-builder/apps/frontend/src/components/WebSocketConnectionGuide.jsx
  my-web-builder/apps/frontend/src/config.js
  my-web-builder/apps/frontend/src/hooks/useCollaboration.js
  my-web-builder/apps/frontend/src/hooks/useCollaborationV2.js
  my-web-builder/apps/frontend/src/index.css
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
  my-web-builder/apps/frontend/src/pages/DraftsPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/PageRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
  package.json
  quick-start-server.sh
  restart-yjs-ssl-server.sh
  setup-remote-yjs.sh
  start-dual-yjs-servers.sh
  start-yjs-server.sh
  stop-yjs-servers.sh
  test-packages.js
  test-templates-api.js
  yjs-server-deployment-guide.md
  yjs-server-dual.js
  yjs-server-mixed.js
  yjs-server-package.json
  yjs-server-userdata.sh
  yjs-server.js
  yjs-server.pid
Labels: 배민재민

#427 Gridgallary z-index값 수정
  my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/ButtonRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/DdayRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/GridGalleryRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/LinkCopyRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/LinkRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MusicRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/PageRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/SlideGalleryRenderer.jsx
Labels: 올영김별

#435 카카오톡 공유하기 배포로직에 key값 추가 , music 컴포넌트 변수 선언 수정
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MapView.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MusicRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MapView.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MusicRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/next.config.js
Labels: 배민재민

#437 typescript 오류 해결
  my-web-builder/apps/subdomain-nextjs/next.config.js
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 배민재민

#438 build 오류 해결
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 배민재민

#439 Next.js 정적 내보내기 설정
  .github/workflows/deploy-frontend.yml
  my-web-builder/apps/subdomain-nextjs/next.config.js
Labels: 배민재민

#440 build 오류 해결
  .github/workflows/deploy-frontend.yml
  .github/workflows/deploy-nextjs.yml
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MapView.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MusicRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MapView.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MusicRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/next.config.js
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 배민재민

#441 빌드 오류 해결
  .github/workflows/deploy-nextjs.yml
Labels: 배민재민

#442 카카오
  .github/workflows/deploy-frontend.yml
  .github/workflows/deploy-nextjs.yml
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MapView.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MapView.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MusicRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
  my-web-builder/apps/subdomain-nextjs/next.config.js
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 배민재민

#446 카카오 구글 오류 해결~~
  backend/src/auth/auth.service.ts
Labels: 배민재민

#450 Iamking
  my-web-builder/apps/frontend/src/components/collaboration/ChatBubble.jsx
  my-web-builder/apps/frontend/src/components/collaboration/ChatInput.jsx
  my-web-builder/apps/frontend/src/hooks/useChat.js
  my-web-builder/apps/frontend/src/hooks/useCollaboration.js
  my-web-builder/apps/frontend/src/hooks/useComponentActions.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
Labels: 배민재민

#454 채팅 중복 id 생성 방지 로직, mac os 채팅보 않는 문제 개선 테스트
  my-web-builder/apps/frontend/src/components/collaboration/ChatBubble.jsx
  my-web-builder/apps/frontend/src/components/collaboration/ChatInput.jsx
  my-web-builder/apps/frontend/src/hooks/useChat.js
  my-web-builder/apps/frontend/src/hooks/useCollaboration.js
Labels: 배민재민

#455 안내장, Slido 한글 입력 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/SlidoEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/TextComponentEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/WeddingInviteEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/TextEditor.jsx
Labels: 인프세창

#459 채팅 기능 커서 옆 이름 아래에 보이게
  my-web-builder/apps/frontend/src/components/collaboration/ChatInput.jsx
  my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
  my-web-builder/apps/frontend/src/hooks/useChat.js
  my-web-builder/apps/frontend/src/hooks/useCollaboration.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
Labels: 배민재민

#461 텍스트 컴포넌트 정렬 기능
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
Labels: 인프세창

#460 dashboard header 수정
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
Labels: 배민재민

#463 텍스트 기본값 중앙 정렬
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/TextComponentEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
Labels: 인프세창

#477 Slido 컴포넌트 디자인 수정 & 컴포넌트 테두리 배포 후 화면 반영
  backend/src/users/users.service.ts
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/SlidoEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/CommentRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/components/definitions/slido.json
  my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/BankAccountRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/CalendarRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/CommentRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/SlideGalleryRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/SlidoRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/WeddingInviteRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 올영김별

#479 fix: GitHub Actions에서 WebSocket URL을 도메인 기반으로 변경
  .github/workflows/deploy-frontend.yml
Labels: 배민재민

#481 Fix UI
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/SearchBar.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendanceSummary.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/Inspector.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
  my-web-builder/apps/frontend/src/styles/global.css
Labels: 올영김별

#485 drafts 페이지, deployed 페이지 수정
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
  my-web-builder/apps/frontend/src/pages/DraftsPage.jsx
Labels: 펍지준배

#486 메인 페이지, 로그인/회원가입, 대쉬보드 디자인 완성
  my-web-builder/apps/frontend/index.html
  my-web-builder/apps/frontend/public/ddukddak-logo.png
  my-web-builder/apps/frontend/src/App.tsx
  my-web-builder/apps/frontend/src/components/NotificationToggle.jsx
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
  my-web-builder/apps/frontend/src/pages/DraftsPage.jsx
  my-web-builder/apps/frontend/src/pages/LoginPage.jsx
  my-web-builder/apps/frontend/src/pages/MainPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
  my-web-builder/apps/frontend/src/pages/SignupPage.jsx
Labels: 올영김별

#489 Fix grid
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
Labels: 펍지준배

#491 메인, 로그인, 회원가입 로고위치 동일, 배포된 페이지, 임시저장, 새로생성된 페이지 동일한 페이지
  backend/src/generator/generator.service.ts
  backend/src/templates/templates.service.ts
  backend/src/users/entities/page_members.entity.ts
  backend/src/users/entities/pages.entity.ts
  backend/src/users/entities/submissions.entity.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  my-web-builder/apps/frontend/src/App.tsx
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
  my-web-builder/apps/frontend/src/pages/DraftsPage.jsx
  my-web-builder/apps/frontend/src/pages/LoginPage.jsx
  my-web-builder/apps/frontend/src/pages/MainPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/SecretPage.jsx
  my-web-builder/apps/frontend/src/pages/SignupPage.jsx
Labels: 배민재민

#492 build error 해결
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
Labels: 배민재민

#493 useEffect 괄호안닫음
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
Labels: 배민재민

#499 최종 배포 모달 디자인 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/DeployModal.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
Labels: 펍지준배

#498 코멘트달때 마우스 오른쪽 버튼 클릭 없앰. 컴포넌트 삭제 backspace 가능
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
Labels: 올영김별

#500 deploy page에서 편집하기 누르면 url에 viewport 파라미터 제거
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
Labels: 배민재민

#501 도메인 에러 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/hooks/useDeploy.js
Labels: 펍지준배

#503 카카오 소셜 오류 해결 테스트
  .github/workflows/deploy-backend.yml
  backend/src/auth/auth.service.ts
  my-web-builder/apps/frontend/src/pages/LoginPage.jsx
  my-web-builder/apps/frontend/src/pages/MainPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/DeployModal.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/InviteModal.jsx
  my-web-builder/apps/frontend/src/pages/SignupPage.jsx
Labels: 배민재민

#507 토스트 알림 고치는 중
  my-web-builder/apps/frontend/src/App.tsx
  my-web-builder/apps/frontend/src/components/InvitationNotifications.jsx
  my-web-builder/apps/frontend/src/components/Toast.jsx
  my-web-builder/apps/frontend/src/components/ToastExample.jsx
  my-web-builder/apps/frontend/src/contexts/ToastContext.jsx
  my-web-builder/apps/frontend/src/hooks/useComponentActions.js
  my-web-builder/apps/frontend/src/hooks/useToast.js
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/InviteModal.jsx
  my-web-builder/apps/frontend/src/pages/SocialCallbackPage.jsx
Labels: 올영김별

#508 deploy frontend yml 수정
  .github/workflows/deploy-frontend.yml
  backend/src/auth/auth.service.ts
  backend/src/main.ts
Labels: 배민재민

#510 토스트 알림 통일 적용
  backend/src/users/users.service.ts
  my-web-builder/apps/frontend/src/components/NotificationToggle.jsx
  my-web-builder/apps/frontend/src/hooks/useEditorInteractionManager.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/KakaoTalkShareEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary.backup.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/BankAccountRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ButtonRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/CommentRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/LinkRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/ImageListEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/ImageSourceEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/ThumbnailEditor.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/ButtonRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/LinkRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx
Labels: 올영김별

#516 폰트 스타일 추가
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/FontFamilyEditor.jsx
  my-web-builder/apps/frontend/src/styles/global.css
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
Labels: 인프세창

#520 Dashboard 템플릿 카드 비율, 미리보기 조정
  my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/hooks/useDeploy.js
Labels: 올영김별

#521 yjs 서버 연결 끊김 현상 useeffect 충돌 제거
  advanced-test-scenarios.js
  artillery-websocket-test.yml
  load-test-setup.sh
  monitor-performance.js
  my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
  my-web-builder/apps/frontend/src/hooks/useCollaboration.js
  my-web-builder/apps/frontend/src/hooks/useLiveCursors.js
  my-web-builder/apps/frontend/src/hooks/useYjsCollaboration.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
  package-lock.json
  package.json
  yjs-server.js
Labels: 배민재민

#525 디데이 컴포넌트 스케일 오류 해결, 주소 owner 재발행 오류 수정, 모달창 디자인 수정
  backend/src/generator/generator.service.ts
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/DdayRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/DeployModal.jsx
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 올영김별

#526 이미지 배포화면 수정
  my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx
Labels: 펍지준배

#527 폰트 미리보기까지는 해결
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
Labels: 인프세창

#528 2차 수정 이미지랜더러
  my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx
Labels: 펍지준배

#530 배포 후 화면 radius 불일치 오류 수정/카카오톡 공유, 링크, 안내장 컴포넌트 수정/컴포넌트 최소 높이 보장
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/LinkRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingInviteRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  my-web-builder/apps/subdomain-nextjs/components/renderers/CalendarRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/LinkRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MapInfoRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/WeddingInviteRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 올영김별

#531 텍스트 컴포넌트 개선, 이미지와 그룹핑, 반응형 적용
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/SlidoRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 올영김별

#532 컴포넌트 축소 문제 해결, 텍스트 세로기준 가운데 정렬, 미리보기 오류 해결,slido 컴포넌트 사이즈 오류 해결
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx
Labels: 올영김별

#533 캔버스 가로 사이즈 에러 해결
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
Labels: 올영김별

#534 로그 일부 삭제, 줌 35%, 채팅 버그 수정
  backend/simple-server.js
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt.strategy.ts
  backend/src/common/guards/jwt-auth.guard.ts
  backend/src/main.ts
  backend/src/templates/templates.service.ts
  collaboration-performance-test.js
  my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
  my-web-builder/apps/frontend/src/hooks/useChat.js
  my-web-builder/apps/frontend/src/hooks/useCollaboration.js
  my-web-builder/apps/frontend/src/hooks/useLiveCursors.js
  my-web-builder/apps/frontend/src/hooks/useYjsCollaboration.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  quick-collaboration-test.js
  run-collaboration-test.sh
Labels: 배민재민

#536 채팅 줌인아웃 영향 x
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
Labels: 배민재민

#537 살려줘
  my-web-builder/apps/frontend/src/hooks/useScaledFontSize.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ButtonRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MapInfoRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingInviteRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  my-web-builder/apps/frontend/src/styles/global.css
  my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MapInfoRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/WeddingInviteRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/hooks/useScaledFontSize.js
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
  my-web-builder/apps/subdomain-nextjs/styles/globals.css
Labels: 올영김별

#542 그리드 갤러리 편집모드에서 상호작용 막음
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/GridGalleryRenderer.jsx
Labels: 펍지준배

#544 모바일 -> 데스크톱 가운데 정렬, 캘린더 서브도메인 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ImageRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/CalendarRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 올영김별

#547 사각형 컴포넌트 추가
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/RectangleLayerEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/RectangleLayerThumbnail.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/index.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/RectangleLayerRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/Inspector.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
  my-web-builder/apps/frontend/src/pages/components/definitions/index.js
  my-web-builder/apps/frontend/src/pages/components/definitions/rectangle-layer.json
  my-web-builder/apps/subdomain-nextjs/components/renderers/RectangleLayerRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/index.js
Labels: 펍지준배

#552 지도 컴포넌트 주소 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx
Labels: 인프세창

#560 콘텐츠 좌표 기준의 통일된 좌표계와 CSS Transform 상쇄 기법을 통해 각 사용자의 줌 레벨과 관계없이 정확한 커서
  my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
  my-web-builder/apps/frontend/src/hooks/useLiveCursors.js
Labels: 배민재민

#561 모바일 뷰 렌더링 이슈 개선
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/CalendarRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/SlidoRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 올영김별

#562 캔버스 확대축소 시 커서 크기 동일, 로그인 된 상태로 mainpage로 이동 시 dashboard로
  my-web-builder/apps/frontend/src/App.tsx
  my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
  my-web-builder/apps/frontend/src/hooks/useLiveCursors.js
Labels: 배민재민

#563 마스터, 일반사용자 확인 섹션 비활성화
  my-web-builder/apps/frontend/src/components/MasterStatusIndicator.jsx
Labels: 배민재민

#565 사각형 컴포넌트 랜더링 고침
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
Labels: 펍지준배

#568 모바일 -> 모바일/데스크톱 오류 수정
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 올영김별

#577 Fix/deployedpage comments improvements
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/CommentRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
  my-web-builder/apps/subdomain-nextjs/pages/_document.js
  my-web-builder/apps/subdomain-nextjs/styles/globals.css
Labels: 스크영준

#580 로그아웃 시 메인 페이지로
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/jwt.strategy.ts
  backend/src/main.ts
  my-web-builder/apps/frontend/src/App.tsx
  my-web-builder/apps/frontend/src/config.js
  my-web-builder/apps/frontend/src/hooks/useAutoSave.js
  my-web-builder/apps/frontend/src/hooks/useLiveCursors.js
  my-web-builder/apps/frontend/src/hooks/useMasterAutoSave.js
  my-web-builder/apps/frontend/src/hooks/useMasterSystem.js
  my-web-builder/apps/frontend/src/hooks/usePageDataManager.js
  my-web-builder/apps/frontend/src/hooks/useYjsCollaboration.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapView.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/MapView.jsx
  my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx
  my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx
Labels: 배민재민

#583 지도 컴포넌트 에디터 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx
Labels: 인프세창

#581 메인페이지에서 시작하기 누르면 로그인 페이지로 이동
  backend/src/auth/auth.service.ts
  my-web-builder/apps/frontend/src/hooks/useComponentActions.js
  my-web-builder/apps/frontend/src/hooks/useMasterSystem.js
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
  my-web-builder/apps/frontend/src/pages/DraftsPage.jsx
  my-web-builder/apps/frontend/src/pages/LoginPage.jsx
  my-web-builder/apps/frontend/src/pages/MainPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  my-web-builder/apps/subdomain-nextjs/next-env.d.ts
Labels: 배민재민

#585 텍스트 에디터 및 댓글에디터 수정
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/CommentEditor.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/TextEditor.jsx
Labels: 인프세창

#586 데스크톱 미리보기, 페이지, 배포 갯수 제한
  backend/src/generator/generator.service.ts
  backend/src/templates/templates.service.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/DeploySection.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/hooks/useDeploy.js
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
Labels: 배민재민

#587 테마에 기타 추가, 페이지 생성시 1초 뒤에 에디터로 넘어가는거 제거
  my-web-builder/apps/frontend/src/hooks/useComponentActions.js
  my-web-builder/apps/frontend/src/hooks/useEditorInteractionManager.js
  my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
  my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/TemplateModal.jsx
Labels: 배민재민
