Repository Jungle-5pointers/5_pointers, pull requests merged in 2025-06, with the labels that each got.

#8 컴포넌트 기초 틀 구성
  backend/package-lock.json
  backend/package.json
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/components/definitions/button.json
  frontend/src/pages/components/definitions/index.js
  frontend/src/pages/components/definitions/link.json
  frontend/src/pages/components/definitions/text.json
Labels: 올영김별

#12 Canvas 레이아웃 수정
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  tree.txt
Labels: 인프세창

#16 컴포넌트 에디터 속성별 분리
  backend/src/main.ts
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/ColorEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/NumberEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/TextEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/index.js
Labels: 펍지준배

#10 DB entity 테이블 추가(page_members, pages, submissions)
  frontend/src/pages/NoCodeEditor.jsx
Labels: 배민재민

#35 Reset: 이미지애디터 및 속성에디터 추가
  frontend/package-lock.json
  frontend/src/FontTest.jsx
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/ButtonEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/ImageEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
  frontend/src/pages/NoCodeEditor/ComponentRenderers/ButtonRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/ImageRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/BorderRadiusEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/FontFamilyEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/ImageSourceEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/LetterSpacingEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/LineHeightEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/NumberEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/ObjectFitEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/TextAlignEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/TextStyleEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/index.js
  frontend/src/pages/components/definitions/button.json
  frontend/src/pages/components/definitions/image.json
  frontend/src/pages/components/definitions/index.js
Labels: 펍지준배

#49 fix: component_mapinfo 브랜치 최종 충돌 해결 및 MapInfo 관련 파일 추가
  frontend/package-lock.json
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/MapInfoEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
  frontend/src/pages/NoCodeEditor/ComponentRenderers/MapInfoRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/components/definitions/index.js
  frontend/src/pages/components/definitions/map_info.json
Labels: 인프세창

#50 갤러리 컴포넌트 추가
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/GridGalleryEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/SlideGalleryEditor.jsx
  frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
  frontend/src/pages/NoCodeEditor/ComponentRenderers/GridGalleryRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/SlideGalleryRenderer.jsx
  frontend/src/pages/NoCodeEditor/ComponentRenderers/SlideGalleryRenderer.jsx.backup
  frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/BooleanEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/ImageListEditor.jsx
  frontend/src/pages/NoCodeEditor/PropertyEditors/index.js
  frontend/src/pages/components/definitions/grid-gallery.json
  frontend/src/pages/components/definitions/index.js
  frontend/src/pages/components/definitions/slide-gallery.json
  mysql-mcp-server/package.json
  package-lock.json
  package.json
Labels: 펍지준배

#55 Fix: 이제 진짜 됨
  frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/components/definitions/index.js
Labels: 펍지준배

#54 feat : 캔버스 제작 중
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/components/definitions/index.js
Labels: 배민재민

#56 오늘의 최고 완벽본
  frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
  frontend/src/pages/NoCodeEditor/Inspector.jsx
Labels: 배민재민

#58 메인 깨지는 현상 고침
  frontend/src/pages/NoCodeEditor/Inspector.jsx
Labels: 올영김별

#59 미리보기 구현
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/Inspector.jsx
  frontend/src/pages/NoCodeEditor/PreviewModal.jsx
  frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
Labels: 배민재민

#63 Canvars 충돌방지, 확장기, 스냅라인
  backend/src/users/users.controller.ts
  frontend/src/pages/NoCodeEditor.jsx
  frontend/src/pages/NoCodeEditor/CanvasArea.jsx
  frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
  frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
  frontend/src/pages/NoCodeEditor/ViewportController.jsx
Labels: 배민재민
